[project]
name = "mypak"
version = "0.0.1"
dependencies = ['shortid>=0.1.2']  # what you need to run the package

[project.optional-dependencies]
dev = ['pytest>=7.0', 'twine>=4.0.2']  # what you need to develop the package
